name: analysis

on: push

env:
  MIX_ENV: test

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24.0.0]
        elixir: [1.12.1]
    steps:
      - name: Cancels previous run
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Retrieve cached deps
        uses: actions/cache@v2
        id: project-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install project deps
        if: steps.project-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix do deps.get, deps.compile
          mix dialyzer --plt

  static_code_analysis:
    name: Static code analysis
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24.0.0]
        elixir: [1.12.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Retrieve cached deps
        uses: actions/cache@v2
        id: project-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Check code format
        run: mix format --check-formatted

      - name: Check code style
        run: mix credo --strict

      - name: Run dialyzer
        run: mix dialyzer --format dialyxir
